/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_pitchdetection_type {
  public final static aubio_pitchdetection_type aubio_pitch_yin = new aubio_pitchdetection_type("aubio_pitch_yin");
  public final static aubio_pitchdetection_type aubio_pitch_mcomb = new aubio_pitchdetection_type("aubio_pitch_mcomb");
  public final static aubio_pitchdetection_type aubio_pitch_schmitt = new aubio_pitchdetection_type("aubio_pitch_schmitt");
  public final static aubio_pitchdetection_type aubio_pitch_fcomb = new aubio_pitchdetection_type("aubio_pitch_fcomb");
  public final static aubio_pitchdetection_type aubio_pitch_yinfft = new aubio_pitchdetection_type("aubio_pitch_yinfft");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_pitchdetection_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_pitchdetection_type.class + " with value " + swigValue);
  }

  private aubio_pitchdetection_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_pitchdetection_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_pitchdetection_type(String swigName, aubio_pitchdetection_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_pitchdetection_type[] swigValues = { aubio_pitch_yin, aubio_pitch_mcomb, aubio_pitch_schmitt, aubio_pitch_fcomb, aubio_pitch_yinfft };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

