/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_onsetdetection_type {
  public final static aubio_onsetdetection_type aubio_onset_energy = new aubio_onsetdetection_type("aubio_onset_energy");
  public final static aubio_onsetdetection_type aubio_onset_specdiff = new aubio_onsetdetection_type("aubio_onset_specdiff");
  public final static aubio_onsetdetection_type aubio_onset_hfc = new aubio_onsetdetection_type("aubio_onset_hfc");
  public final static aubio_onsetdetection_type aubio_onset_complex = new aubio_onsetdetection_type("aubio_onset_complex");
  public final static aubio_onsetdetection_type aubio_onset_phase = new aubio_onsetdetection_type("aubio_onset_phase");
  public final static aubio_onsetdetection_type aubio_onset_kl = new aubio_onsetdetection_type("aubio_onset_kl");
  public final static aubio_onsetdetection_type aubio_onset_mkl = new aubio_onsetdetection_type("aubio_onset_mkl");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_onsetdetection_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_onsetdetection_type.class + " with value " + swigValue);
  }

  private aubio_onsetdetection_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_onsetdetection_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_onsetdetection_type(String swigName, aubio_onsetdetection_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_onsetdetection_type[] swigValues = { aubio_onset_energy, aubio_onset_specdiff, aubio_onset_hfc, aubio_onset_complex, aubio_onset_phase, aubio_onset_kl, aubio_onset_mkl };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

