/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_player_status {
  public final static aubio_player_status AUBIO_MIDI_PLAYER_READY = new aubio_player_status("AUBIO_MIDI_PLAYER_READY");
  public final static aubio_player_status AUBIO_MIDI_PLAYER_PLAYING = new aubio_player_status("AUBIO_MIDI_PLAYER_PLAYING");
  public final static aubio_player_status AUBIO_MIDI_PLAYER_DONE = new aubio_player_status("AUBIO_MIDI_PLAYER_DONE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_player_status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_player_status.class + " with value " + swigValue);
  }

  private aubio_player_status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_player_status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_player_status(String swigName, aubio_player_status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_player_status[] swigValues = { AUBIO_MIDI_PLAYER_READY, AUBIO_MIDI_PLAYER_PLAYING, AUBIO_MIDI_PLAYER_DONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

