/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_window_type {
  public final static aubio_window_type aubio_win_rectangle = new aubio_window_type("aubio_win_rectangle");
  public final static aubio_window_type aubio_win_hamming = new aubio_window_type("aubio_win_hamming");
  public final static aubio_window_type aubio_win_hanning = new aubio_window_type("aubio_win_hanning");
  public final static aubio_window_type aubio_win_hanningz = new aubio_window_type("aubio_win_hanningz");
  public final static aubio_window_type aubio_win_blackman = new aubio_window_type("aubio_win_blackman");
  public final static aubio_window_type aubio_win_blackman_harris = new aubio_window_type("aubio_win_blackman_harris");
  public final static aubio_window_type aubio_win_gaussian = new aubio_window_type("aubio_win_gaussian");
  public final static aubio_window_type aubio_win_welch = new aubio_window_type("aubio_win_welch");
  public final static aubio_window_type aubio_win_parzen = new aubio_window_type("aubio_win_parzen");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_window_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_window_type.class + " with value " + swigValue);
  }

  private aubio_window_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_window_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_window_type(String swigName, aubio_window_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_window_type[] swigValues = { aubio_win_rectangle, aubio_win_hamming, aubio_win_hanning, aubio_win_hanningz, aubio_win_blackman, aubio_win_blackman_harris, aubio_win_gaussian, aubio_win_welch, aubio_win_parzen };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

