/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_midi_control_change {
  public final static aubio_midi_control_change BANK_SELECT_MSB = new aubio_midi_control_change("BANK_SELECT_MSB", aubiowrapperJNI.BANK_SELECT_MSB_get());
  public final static aubio_midi_control_change MODULATION_MSB = new aubio_midi_control_change("MODULATION_MSB", aubiowrapperJNI.MODULATION_MSB_get());
  public final static aubio_midi_control_change BREATH_MSB = new aubio_midi_control_change("BREATH_MSB", aubiowrapperJNI.BREATH_MSB_get());
  public final static aubio_midi_control_change FOOT_MSB = new aubio_midi_control_change("FOOT_MSB", aubiowrapperJNI.FOOT_MSB_get());
  public final static aubio_midi_control_change PORTAMENTO_TIME_MSB = new aubio_midi_control_change("PORTAMENTO_TIME_MSB", aubiowrapperJNI.PORTAMENTO_TIME_MSB_get());
  public final static aubio_midi_control_change DATA_ENTRY_MSB = new aubio_midi_control_change("DATA_ENTRY_MSB", aubiowrapperJNI.DATA_ENTRY_MSB_get());
  public final static aubio_midi_control_change VOLUME_MSB = new aubio_midi_control_change("VOLUME_MSB", aubiowrapperJNI.VOLUME_MSB_get());
  public final static aubio_midi_control_change BALANCE_MSB = new aubio_midi_control_change("BALANCE_MSB", aubiowrapperJNI.BALANCE_MSB_get());
  public final static aubio_midi_control_change PAN_MSB = new aubio_midi_control_change("PAN_MSB", aubiowrapperJNI.PAN_MSB_get());
  public final static aubio_midi_control_change EXPRESSION_MSB = new aubio_midi_control_change("EXPRESSION_MSB", aubiowrapperJNI.EXPRESSION_MSB_get());
  public final static aubio_midi_control_change EFFECTS1_MSB = new aubio_midi_control_change("EFFECTS1_MSB", aubiowrapperJNI.EFFECTS1_MSB_get());
  public final static aubio_midi_control_change EFFECTS2_MSB = new aubio_midi_control_change("EFFECTS2_MSB", aubiowrapperJNI.EFFECTS2_MSB_get());
  public final static aubio_midi_control_change GPC1_MSB = new aubio_midi_control_change("GPC1_MSB", aubiowrapperJNI.GPC1_MSB_get());
  public final static aubio_midi_control_change GPC2_MSB = new aubio_midi_control_change("GPC2_MSB", aubiowrapperJNI.GPC2_MSB_get());
  public final static aubio_midi_control_change GPC3_MSB = new aubio_midi_control_change("GPC3_MSB", aubiowrapperJNI.GPC3_MSB_get());
  public final static aubio_midi_control_change GPC4_MSB = new aubio_midi_control_change("GPC4_MSB", aubiowrapperJNI.GPC4_MSB_get());
  public final static aubio_midi_control_change BANK_SELECT_LSB = new aubio_midi_control_change("BANK_SELECT_LSB", aubiowrapperJNI.BANK_SELECT_LSB_get());
  public final static aubio_midi_control_change MODULATION_WHEEL_LSB = new aubio_midi_control_change("MODULATION_WHEEL_LSB", aubiowrapperJNI.MODULATION_WHEEL_LSB_get());
  public final static aubio_midi_control_change BREATH_LSB = new aubio_midi_control_change("BREATH_LSB", aubiowrapperJNI.BREATH_LSB_get());
  public final static aubio_midi_control_change FOOT_LSB = new aubio_midi_control_change("FOOT_LSB", aubiowrapperJNI.FOOT_LSB_get());
  public final static aubio_midi_control_change PORTAMENTO_TIME_LSB = new aubio_midi_control_change("PORTAMENTO_TIME_LSB", aubiowrapperJNI.PORTAMENTO_TIME_LSB_get());
  public final static aubio_midi_control_change DATA_ENTRY_LSB = new aubio_midi_control_change("DATA_ENTRY_LSB", aubiowrapperJNI.DATA_ENTRY_LSB_get());
  public final static aubio_midi_control_change VOLUME_LSB = new aubio_midi_control_change("VOLUME_LSB", aubiowrapperJNI.VOLUME_LSB_get());
  public final static aubio_midi_control_change BALANCE_LSB = new aubio_midi_control_change("BALANCE_LSB", aubiowrapperJNI.BALANCE_LSB_get());
  public final static aubio_midi_control_change PAN_LSB = new aubio_midi_control_change("PAN_LSB", aubiowrapperJNI.PAN_LSB_get());
  public final static aubio_midi_control_change EXPRESSION_LSB = new aubio_midi_control_change("EXPRESSION_LSB", aubiowrapperJNI.EXPRESSION_LSB_get());
  public final static aubio_midi_control_change EFFECTS1_LSB = new aubio_midi_control_change("EFFECTS1_LSB", aubiowrapperJNI.EFFECTS1_LSB_get());
  public final static aubio_midi_control_change EFFECTS2_LSB = new aubio_midi_control_change("EFFECTS2_LSB", aubiowrapperJNI.EFFECTS2_LSB_get());
  public final static aubio_midi_control_change GPC1_LSB = new aubio_midi_control_change("GPC1_LSB", aubiowrapperJNI.GPC1_LSB_get());
  public final static aubio_midi_control_change GPC2_LSB = new aubio_midi_control_change("GPC2_LSB", aubiowrapperJNI.GPC2_LSB_get());
  public final static aubio_midi_control_change GPC3_LSB = new aubio_midi_control_change("GPC3_LSB", aubiowrapperJNI.GPC3_LSB_get());
  public final static aubio_midi_control_change GPC4_LSB = new aubio_midi_control_change("GPC4_LSB", aubiowrapperJNI.GPC4_LSB_get());
  public final static aubio_midi_control_change SUSTAIN_SWITCH = new aubio_midi_control_change("SUSTAIN_SWITCH", aubiowrapperJNI.SUSTAIN_SWITCH_get());
  public final static aubio_midi_control_change PORTAMENTO_SWITCH = new aubio_midi_control_change("PORTAMENTO_SWITCH", aubiowrapperJNI.PORTAMENTO_SWITCH_get());
  public final static aubio_midi_control_change SOSTENUTO_SWITCH = new aubio_midi_control_change("SOSTENUTO_SWITCH", aubiowrapperJNI.SOSTENUTO_SWITCH_get());
  public final static aubio_midi_control_change SOFT_PEDAL_SWITCH = new aubio_midi_control_change("SOFT_PEDAL_SWITCH", aubiowrapperJNI.SOFT_PEDAL_SWITCH_get());
  public final static aubio_midi_control_change LEGATO_SWITCH = new aubio_midi_control_change("LEGATO_SWITCH", aubiowrapperJNI.LEGATO_SWITCH_get());
  public final static aubio_midi_control_change HOLD2_SWITCH = new aubio_midi_control_change("HOLD2_SWITCH", aubiowrapperJNI.HOLD2_SWITCH_get());
  public final static aubio_midi_control_change SOUND_CTRL1 = new aubio_midi_control_change("SOUND_CTRL1", aubiowrapperJNI.SOUND_CTRL1_get());
  public final static aubio_midi_control_change SOUND_CTRL2 = new aubio_midi_control_change("SOUND_CTRL2", aubiowrapperJNI.SOUND_CTRL2_get());
  public final static aubio_midi_control_change SOUND_CTRL3 = new aubio_midi_control_change("SOUND_CTRL3", aubiowrapperJNI.SOUND_CTRL3_get());
  public final static aubio_midi_control_change SOUND_CTRL4 = new aubio_midi_control_change("SOUND_CTRL4", aubiowrapperJNI.SOUND_CTRL4_get());
  public final static aubio_midi_control_change SOUND_CTRL5 = new aubio_midi_control_change("SOUND_CTRL5", aubiowrapperJNI.SOUND_CTRL5_get());
  public final static aubio_midi_control_change SOUND_CTRL6 = new aubio_midi_control_change("SOUND_CTRL6", aubiowrapperJNI.SOUND_CTRL6_get());
  public final static aubio_midi_control_change SOUND_CTRL7 = new aubio_midi_control_change("SOUND_CTRL7", aubiowrapperJNI.SOUND_CTRL7_get());
  public final static aubio_midi_control_change SOUND_CTRL8 = new aubio_midi_control_change("SOUND_CTRL8", aubiowrapperJNI.SOUND_CTRL8_get());
  public final static aubio_midi_control_change SOUND_CTRL9 = new aubio_midi_control_change("SOUND_CTRL9", aubiowrapperJNI.SOUND_CTRL9_get());
  public final static aubio_midi_control_change SOUND_CTRL10 = new aubio_midi_control_change("SOUND_CTRL10", aubiowrapperJNI.SOUND_CTRL10_get());
  public final static aubio_midi_control_change GPC5 = new aubio_midi_control_change("GPC5", aubiowrapperJNI.GPC5_get());
  public final static aubio_midi_control_change GPC6 = new aubio_midi_control_change("GPC6", aubiowrapperJNI.GPC6_get());
  public final static aubio_midi_control_change GPC7 = new aubio_midi_control_change("GPC7", aubiowrapperJNI.GPC7_get());
  public final static aubio_midi_control_change GPC8 = new aubio_midi_control_change("GPC8", aubiowrapperJNI.GPC8_get());
  public final static aubio_midi_control_change PORTAMENTO_CTRL = new aubio_midi_control_change("PORTAMENTO_CTRL", aubiowrapperJNI.PORTAMENTO_CTRL_get());
  public final static aubio_midi_control_change EFFECTS_DEPTH1 = new aubio_midi_control_change("EFFECTS_DEPTH1", aubiowrapperJNI.EFFECTS_DEPTH1_get());
  public final static aubio_midi_control_change EFFECTS_DEPTH2 = new aubio_midi_control_change("EFFECTS_DEPTH2", aubiowrapperJNI.EFFECTS_DEPTH2_get());
  public final static aubio_midi_control_change EFFECTS_DEPTH3 = new aubio_midi_control_change("EFFECTS_DEPTH3", aubiowrapperJNI.EFFECTS_DEPTH3_get());
  public final static aubio_midi_control_change EFFECTS_DEPTH4 = new aubio_midi_control_change("EFFECTS_DEPTH4", aubiowrapperJNI.EFFECTS_DEPTH4_get());
  public final static aubio_midi_control_change EFFECTS_DEPTH5 = new aubio_midi_control_change("EFFECTS_DEPTH5", aubiowrapperJNI.EFFECTS_DEPTH5_get());
  public final static aubio_midi_control_change DATA_ENTRY_INCR = new aubio_midi_control_change("DATA_ENTRY_INCR", aubiowrapperJNI.DATA_ENTRY_INCR_get());
  public final static aubio_midi_control_change DATA_ENTRY_DECR = new aubio_midi_control_change("DATA_ENTRY_DECR", aubiowrapperJNI.DATA_ENTRY_DECR_get());
  public final static aubio_midi_control_change NRPN_LSB = new aubio_midi_control_change("NRPN_LSB", aubiowrapperJNI.NRPN_LSB_get());
  public final static aubio_midi_control_change NRPN_MSB = new aubio_midi_control_change("NRPN_MSB", aubiowrapperJNI.NRPN_MSB_get());
  public final static aubio_midi_control_change RPN_LSB = new aubio_midi_control_change("RPN_LSB", aubiowrapperJNI.RPN_LSB_get());
  public final static aubio_midi_control_change RPN_MSB = new aubio_midi_control_change("RPN_MSB", aubiowrapperJNI.RPN_MSB_get());
  public final static aubio_midi_control_change ALL_SOUND_OFF = new aubio_midi_control_change("ALL_SOUND_OFF", aubiowrapperJNI.ALL_SOUND_OFF_get());
  public final static aubio_midi_control_change ALL_CTRL_OFF = new aubio_midi_control_change("ALL_CTRL_OFF", aubiowrapperJNI.ALL_CTRL_OFF_get());
  public final static aubio_midi_control_change LOCAL_CONTROL = new aubio_midi_control_change("LOCAL_CONTROL", aubiowrapperJNI.LOCAL_CONTROL_get());
  public final static aubio_midi_control_change ALL_NOTES_OFF = new aubio_midi_control_change("ALL_NOTES_OFF", aubiowrapperJNI.ALL_NOTES_OFF_get());
  public final static aubio_midi_control_change OMNI_OFF = new aubio_midi_control_change("OMNI_OFF", aubiowrapperJNI.OMNI_OFF_get());
  public final static aubio_midi_control_change OMNI_ON = new aubio_midi_control_change("OMNI_ON", aubiowrapperJNI.OMNI_ON_get());
  public final static aubio_midi_control_change POLY_OFF = new aubio_midi_control_change("POLY_OFF", aubiowrapperJNI.POLY_OFF_get());
  public final static aubio_midi_control_change POLY_ON = new aubio_midi_control_change("POLY_ON", aubiowrapperJNI.POLY_ON_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_midi_control_change swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_midi_control_change.class + " with value " + swigValue);
  }

  private aubio_midi_control_change(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_midi_control_change(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_midi_control_change(String swigName, aubio_midi_control_change swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_midi_control_change[] swigValues = { BANK_SELECT_MSB, MODULATION_MSB, BREATH_MSB, FOOT_MSB, PORTAMENTO_TIME_MSB, DATA_ENTRY_MSB, VOLUME_MSB, BALANCE_MSB, PAN_MSB, EXPRESSION_MSB, EFFECTS1_MSB, EFFECTS2_MSB, GPC1_MSB, GPC2_MSB, GPC3_MSB, GPC4_MSB, BANK_SELECT_LSB, MODULATION_WHEEL_LSB, BREATH_LSB, FOOT_LSB, PORTAMENTO_TIME_LSB, DATA_ENTRY_LSB, VOLUME_LSB, BALANCE_LSB, PAN_LSB, EXPRESSION_LSB, EFFECTS1_LSB, EFFECTS2_LSB, GPC1_LSB, GPC2_LSB, GPC3_LSB, GPC4_LSB, SUSTAIN_SWITCH, PORTAMENTO_SWITCH, SOSTENUTO_SWITCH, SOFT_PEDAL_SWITCH, LEGATO_SWITCH, HOLD2_SWITCH, SOUND_CTRL1, SOUND_CTRL2, SOUND_CTRL3, SOUND_CTRL4, SOUND_CTRL5, SOUND_CTRL6, SOUND_CTRL7, SOUND_CTRL8, SOUND_CTRL9, SOUND_CTRL10, GPC5, GPC6, GPC7, GPC8, PORTAMENTO_CTRL, EFFECTS_DEPTH1, EFFECTS_DEPTH2, EFFECTS_DEPTH3, EFFECTS_DEPTH4, EFFECTS_DEPTH5, DATA_ENTRY_INCR, DATA_ENTRY_DECR, NRPN_LSB, NRPN_MSB, RPN_LSB, RPN_MSB, ALL_SOUND_OFF, ALL_CTRL_OFF, LOCAL_CONTROL, ALL_NOTES_OFF, OMNI_OFF, OMNI_ON, POLY_OFF, POLY_ON };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

