/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_pitchdetection_mode {
  public final static aubio_pitchdetection_mode aubio_pitchm_freq = new aubio_pitchdetection_mode("aubio_pitchm_freq");
  public final static aubio_pitchdetection_mode aubio_pitchm_midi = new aubio_pitchdetection_mode("aubio_pitchm_midi");
  public final static aubio_pitchdetection_mode aubio_pitchm_cent = new aubio_pitchdetection_mode("aubio_pitchm_cent");
  public final static aubio_pitchdetection_mode aubio_pitchm_bin = new aubio_pitchdetection_mode("aubio_pitchm_bin");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_pitchdetection_mode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_pitchdetection_mode.class + " with value " + swigValue);
  }

  private aubio_pitchdetection_mode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_pitchdetection_mode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_pitchdetection_mode(String swigName, aubio_pitchdetection_mode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_pitchdetection_mode[] swigValues = { aubio_pitchm_freq, aubio_pitchm_midi, aubio_pitchm_cent, aubio_pitchm_bin };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

