/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package aubio;

public final class aubio_midi_event_type {
  public final static aubio_midi_event_type NOTE_OFF = new aubio_midi_event_type("NOTE_OFF", aubiowrapperJNI.NOTE_OFF_get());
  public final static aubio_midi_event_type NOTE_ON = new aubio_midi_event_type("NOTE_ON", aubiowrapperJNI.NOTE_ON_get());
  public final static aubio_midi_event_type KEY_PRESSURE = new aubio_midi_event_type("KEY_PRESSURE", aubiowrapperJNI.KEY_PRESSURE_get());
  public final static aubio_midi_event_type CONTROL_CHANGE = new aubio_midi_event_type("CONTROL_CHANGE", aubiowrapperJNI.CONTROL_CHANGE_get());
  public final static aubio_midi_event_type PROGRAM_CHANGE = new aubio_midi_event_type("PROGRAM_CHANGE", aubiowrapperJNI.PROGRAM_CHANGE_get());
  public final static aubio_midi_event_type CHANNEL_PRESSURE = new aubio_midi_event_type("CHANNEL_PRESSURE", aubiowrapperJNI.CHANNEL_PRESSURE_get());
  public final static aubio_midi_event_type PITCH_BEND = new aubio_midi_event_type("PITCH_BEND", aubiowrapperJNI.PITCH_BEND_get());
  public final static aubio_midi_event_type MIDI_SYSEX = new aubio_midi_event_type("MIDI_SYSEX", aubiowrapperJNI.MIDI_SYSEX_get());
  public final static aubio_midi_event_type MIDI_TIME_CODE = new aubio_midi_event_type("MIDI_TIME_CODE", aubiowrapperJNI.MIDI_TIME_CODE_get());
  public final static aubio_midi_event_type MIDI_SONG_POSITION = new aubio_midi_event_type("MIDI_SONG_POSITION", aubiowrapperJNI.MIDI_SONG_POSITION_get());
  public final static aubio_midi_event_type MIDI_SONG_SELECT = new aubio_midi_event_type("MIDI_SONG_SELECT", aubiowrapperJNI.MIDI_SONG_SELECT_get());
  public final static aubio_midi_event_type MIDI_TUNE_REQUEST = new aubio_midi_event_type("MIDI_TUNE_REQUEST", aubiowrapperJNI.MIDI_TUNE_REQUEST_get());
  public final static aubio_midi_event_type MIDI_EOX = new aubio_midi_event_type("MIDI_EOX", aubiowrapperJNI.MIDI_EOX_get());
  public final static aubio_midi_event_type MIDI_SYNC = new aubio_midi_event_type("MIDI_SYNC", aubiowrapperJNI.MIDI_SYNC_get());
  public final static aubio_midi_event_type MIDI_TICK = new aubio_midi_event_type("MIDI_TICK", aubiowrapperJNI.MIDI_TICK_get());
  public final static aubio_midi_event_type MIDI_START = new aubio_midi_event_type("MIDI_START", aubiowrapperJNI.MIDI_START_get());
  public final static aubio_midi_event_type MIDI_CONTINUE = new aubio_midi_event_type("MIDI_CONTINUE", aubiowrapperJNI.MIDI_CONTINUE_get());
  public final static aubio_midi_event_type MIDI_STOP = new aubio_midi_event_type("MIDI_STOP", aubiowrapperJNI.MIDI_STOP_get());
  public final static aubio_midi_event_type MIDI_ACTIVE_SENSING = new aubio_midi_event_type("MIDI_ACTIVE_SENSING", aubiowrapperJNI.MIDI_ACTIVE_SENSING_get());
  public final static aubio_midi_event_type MIDI_SYSTEM_RESET = new aubio_midi_event_type("MIDI_SYSTEM_RESET", aubiowrapperJNI.MIDI_SYSTEM_RESET_get());
  public final static aubio_midi_event_type MIDI_META_EVENT = new aubio_midi_event_type("MIDI_META_EVENT", aubiowrapperJNI.MIDI_META_EVENT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static aubio_midi_event_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + aubio_midi_event_type.class + " with value " + swigValue);
  }

  private aubio_midi_event_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private aubio_midi_event_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private aubio_midi_event_type(String swigName, aubio_midi_event_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static aubio_midi_event_type[] swigValues = { NOTE_OFF, NOTE_ON, KEY_PRESSURE, CONTROL_CHANGE, PROGRAM_CHANGE, CHANNEL_PRESSURE, PITCH_BEND, MIDI_SYSEX, MIDI_TIME_CODE, MIDI_SONG_POSITION, MIDI_SONG_SELECT, MIDI_TUNE_REQUEST, MIDI_EOX, MIDI_SYNC, MIDI_TICK, MIDI_START, MIDI_CONTINUE, MIDI_STOP, MIDI_ACTIVE_SENSING, MIDI_SYSTEM_RESET, MIDI_META_EVENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

