/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "jack/jack.h"

	float phase = 0.0f;

	typedef struct {
		jack_client_t * client;
		JNIEnv * 		env;
		jclass 			cls;
		jmethodID 		mid;
	    jobject 		obj_callback;
		int 			attached;
//		jack_port_t * 	port;
	} UserData;

	JavaVM * virtual_machine = NULL;

	int callback(jack_nframes_t nframes, void * arg) {
		int ret = 0;
		UserData * data;
//		char ** ports;
//		jack_default_audio_sample_t * sampleBuffer;
//		jobject buffer;
		
//		printf("C::callback(%d)\n", nframes); fflush(stdout);
		
		data = (UserData *) arg;
		if (data == NULL) {
			printf("jack: there is no user data...\n"); fflush(stdout);
		}

		if (data->attached == 0) {
			data->attached = 1;
			(*virtual_machine)->AttachCurrentThreadAsDaemon(virtual_machine, (void **) &data->env, NULL);
			data->cls = (*data->env)->FindClass(data->env, "jjack/JackCallback");
			data->mid = (*data->env)->GetMethodID(data->env, data->cls, "process", "(ID)I");
//			data->mid = (*data->env)->GetMethodID(data->env, data->cls, "process", "(Ljava/nio/ByteBuffer;ID)I");
		}

/*
		if (data->port == NULL) {
			ports = jack_get_ports(data->client,jack_get_client_name(data->client),NULL,0);
			if (ports != NULL) {
				data->port = jack_port_by_name(data->client,ports[0]);
			}
//			while (*ports != NULL) {
//				printf("port = %s\n", *ports); fflush(stdout);
//				ports++;
//			}
		}

		if (data->port != NULL) {
			sampleBuffer = (jack_default_audio_sample_t *) jack_port_get_buffer(data->port,nframes);
			buffer = (*data->env)->NewDirectByteBuffer((data->env), sampleBuffer, nframes * sizeof(jack_default_audio_sample_t));
			ret = (int)(*data->env)->CallIntMethod(data->env, data->obj_callback, data->mid,
														buffer,
														nframes,
														0.0);
		}
*/

		ret = (int)(*data->env)->CallIntMethod(data->env, data->obj_callback, data->mid,
													nframes,
													0.0);

		return ret;
	}

	/*
	void shutdown (void * arg) {
		UserData * data;
		printf("C::shutdown()\n"); fflush(stdout);
		data = (UserData *) arg;
		if (data == NULL) {
			printf("jack: there is no user data...\n"); fflush(stdout);
		}
		(*data->env)->DeleteGlobalRef(data->env, data->obj_callback);
	}
	*/

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jstring JNICALL Java_jjack_jjackJNI_JACK_1DEFAULT_1AUDIO_1TYPE_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *) "32 bit float mono audio";
  
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_jjack_jjackJNI_JACK_1DEFAULT_1MIDI_1TYPE_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *) "8 bit raw midi";
  
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortIsInput_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackPortFlags result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackPortFlags)JackPortIsInput;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortIsOutput_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackPortFlags result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackPortFlags)JackPortIsOutput;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortIsPhysical_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackPortFlags result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackPortFlags)JackPortIsPhysical;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortCanMonitor_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackPortFlags result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackPortFlags)JackPortCanMonitor;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortIsTerminal_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackPortFlags result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackPortFlags)JackPortIsTerminal;
  jresult = (jint)result; 
  return jresult;
}


//SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackPortIsActive_1get(JNIEnv *jenv, jclass jcls) {
//  jint jresult = 0 ;
//  enum JackPortFlags result;
//
//  (void)jenv;
//  (void)jcls;
//  result = (enum JackPortFlags)JackPortIsActive;
//  jresult = (jint)result;
//  return jresult;
//}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackNullOption_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackNullOption;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackNoStartServer_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackNoStartServer;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackUseExactName_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackUseExactName;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackServerName_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackServerName;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackLoadName_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackLoadName;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_JackLoadInit_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum JackOptions result;
  
  (void)jenv;
  (void)jcls;
  result = (enum JackOptions)JackLoadInit;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1client_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1; 
  result = (int)jack_client_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_jjack_jjackJNI_jack_1client_1open(JNIEnv *jenv, jclass jcls, jstring jarg1, jobject jarg2) {
  UserData * data;
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  jack_client_t *client = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }

  client = (jack_client_t *)jack_client_open((char const *)arg1,JackNullOption,NULL);
  *(jack_client_t **)&jresult = client;

	// Gets the virtual machine
  if (virtual_machine == NULL) {
	  (*jenv)->GetJavaVM(jenv, &virtual_machine);
  }

    // Creates userData and set parameters
	data = (UserData *)malloc(sizeof(UserData));
	data->attached = 0;
	data->obj_callback = (*jenv)->NewGlobalRef(jenv, jarg2);
	data->client = client;
//	data->port = NULL;
	jack_set_process_callback(client,callback,(void *)data);

  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1get_1sample_1rate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_nframes_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1; 
  result = (jack_nframes_t)jack_get_sample_rate(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_jjack_jjackJNI_jack_1port_1register(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  unsigned long arg4 ;
  jack_port_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (unsigned long)jarg4; 

  result = (jack_port_t *)jack_port_register(arg1,(char const *)arg2,(char const *)arg3,arg4,0);
  
  if (result == NULL) {
  	printf("WARNING!!! result = NULL\n"); fflush(stdout);
  }

  *(jack_port_t **)&jresult = result;
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1port_1unregister(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_port_t *arg2 = (jack_port_t *) 0 ;
  int result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  arg2 = *(jack_port_t **)&jarg2;
  result = (int)jack_port_unregister(arg1,arg2);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1activate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  result = (int)jack_activate(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jobjectArray JNICALL Java_jjack_jjackJNI_jack_1get_1ports(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jobjectArray jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  unsigned long arg4 ;
  char **result = 0 ;
  arg1 = *(jack_client_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (unsigned long)jarg4; 
  result = (char **)jack_get_ports(arg1,(char const *)arg2,(char const *)arg3,arg4);
  if (result == NULL) {
	  jresult == NULL;
  } else {
    int i;
    int len=0;
    jclass clazz;
    jstring temp_string;
    clazz = (*jenv)->FindClass(jenv, "java/lang/String");
    while (result[len]) len++;
    jresult = (*jenv)->NewObjectArray(jenv, len, clazz, NULL);
    for (i=0; i<len; i++) {
      temp_string = (*jenv)->NewStringUTF(jenv, *result++);
      (*jenv)->SetObjectArrayElement(jenv, jresult, i, temp_string);
      (*jenv)->DeleteLocalRef(jenv, temp_string);
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1connect(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)jack_connect(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1disconnect(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)jack_disconnect(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result;
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_jjack_jjackJNI_jack_1port_1name(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  jack_port_t *arg1 = (jack_port_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(jack_port_t **)&jarg1; 
  result = (char *)jack_port_name((jack_port_t const *)arg1);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_jjack_jjackJNI_jack_1port_1get_1buffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  jack_port_t *arg1 = (jack_port_t *) 0 ;
  jack_nframes_t arg2 ;
  void *result = 0 ;
  jack_default_audio_sample_t * sampleBuffer;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_port_t **)&jarg1;
  arg2 = (jack_nframes_t)jarg2;
  sampleBuffer = (jack_default_audio_sample_t *) jack_port_get_buffer(arg1,arg2);
  *(void **)&jresult = result;

	if (sampleBuffer != NULL) {
  	return (*jenv)->NewDirectByteBuffer(jenv, sampleBuffer, (jint) jarg2 * sizeof(jack_default_audio_sample_t));
  }
  else {
  	return NULL;
  }
  

//  return jresult;
}


//SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1set_1process_1callback(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg2) {
//	UserData * data;
//	int err;
//  jint jresult = 0 ;
//  jack_client_t *client = (jack_client_t *) 0 ;
//  int result;
//
//  (void)jenv;
//  (void)jcls;
//  client = *(jack_client_t **)&jarg1;
//
//	// Creates userData and set parameters
//	data = (UserData *)malloc(sizeof(UserData));
//	data->attached = 0;
//	data->obj_callback = (*jenv)->NewGlobalRef(jenv, jarg2);
//
//  result = (int)jack_set_process_callback(client,callback,(void *)data);
//  jresult = (jint)result;
//  return jresult;
//}


SWIGEXPORT jlong JNICALL Java_jjack_jjackJNI_jack_1port_1by_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  char *arg2 = (char *) 0 ;
  jack_port_t *result = 0 ;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (jack_port_t *)jack_port_by_name(arg1,(char const *)arg2);
  *(jack_port_t **)&jresult = result;
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1port_1get_1latency(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_port_t *arg1 = (jack_port_t *) 0 ;
  jack_nframes_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_port_t **)&jarg1;
  result = (jack_nframes_t)jack_port_get_latency(arg1);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1port_1get_1total_1latency(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_port_t *arg2 = (jack_port_t *) 0 ;
  jack_nframes_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  arg2 = *(jack_port_t **)&jarg2;
  result = (jack_nframes_t)jack_port_get_total_latency(arg1,arg2);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1frames_1since_1cycle_1start(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_nframes_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  result = (jack_nframes_t)jack_frames_since_cycle_start((jack_client_t const *)arg1);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1frame_1time(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_nframes_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  result = (jack_nframes_t)jack_frame_time((jack_client_t const *)arg1);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1last_1frame_1time(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_nframes_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  result = (jack_nframes_t)jack_last_frame_time((jack_client_t const *)arg1);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_jjack_jjackJNI_jack_1frames_1to_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_nframes_t arg2 ;
  jack_time_t result;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  arg2 = (jack_nframes_t)jarg2;
  result = jack_frames_to_time((jack_client_t const *)arg1,arg2);
  jresult = (jlong)result;

  return jresult;
}


SWIGEXPORT jint JNICALL Java_jjack_jjackJNI_jack_1time_1to_1frames(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  jack_client_t *arg1 = (jack_client_t *) 0 ;
  jack_time_t arg2 ;
  jack_nframes_t result;
  jack_time_t *argp2 ;

  (void)jenv;
  (void)jcls;
  arg1 = *(jack_client_t **)&jarg1;
  argp2 = *(jack_time_t **)&jarg2;
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null jack_time_t");
    return 0;
  }
  arg2 = *argp2;
  result = (jack_nframes_t)jack_time_to_frames((jack_client_t const *)arg1,arg2);
  jresult = (jint)result;
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_jjack_jjackJNI_jack_1get_1time(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  jack_time_t result;

  (void)jenv;
  (void)jcls;
  result = (jack_time_t)jack_get_time();
  jresult = (jlong) result;

  return jresult;
}


#ifdef __cplusplus
}
#endif

