/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_boris_jvst_JNI */

#define WIN32_LEAN_MEAN
#include <windows.h>
#include "aeffectx.h"

#ifndef _Included_org_boris_jvst_JNI
#define _Included_org_boris_jvst_JNI

extern "C" {

/*
 * Class:     org_boris_jvst_JNI
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_boris_jvst_JNI_loadLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    freeLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_boris_jvst_JNI_freeLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    loadEffect
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_boris_jvst_JNI_loadEffect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    fillEffect
 * Signature: (JJLorg/boris/jvst/AEffect;)V
 */
JNIEXPORT void JNICALL Java_org_boris_jvst_JNI_fillEffect
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    dispatcher
 * Signature: (JIIJJF)I
 */
JNIEXPORT jint JNICALL Java_org_boris_jvst_JNI_dispatcher
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong, jfloat);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    canDo
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_boris_jvst_JNI_canDo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    getPinProperties
 * Signature: (JIZ)Lorg/boris/jvst/struct/VstPinProperties;
 */
JNIEXPORT jobject JNICALL Java_org_boris_jvst_JNI_getPinProperties
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    getParameterProperties
 * Signature: (JI)Lorg/boris/jvst/struct/VstParameterProperties;
 */
JNIEXPORT jobject JNICALL Java_org_boris_jvst_JNI_getParameterProperties
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    editGetRect
 * Signature: (J)Lorg/boris/jvst/struct/ERect;
 */
JNIEXPORT jobject JNICALL Java_org_boris_jvst_JNI_editGetRect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    dispatcherS
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_boris_jvst_JNI_dispatcherS
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    setParameter
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_org_boris_jvst_JNI_setParameter
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    getParameter
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_boris_jvst_JNI_getParameter
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_boris_jvst_JNI
 * Method:    processReplacing
 * Signature: (J[[F[[FI)V
 */
JNIEXPORT void JNICALL Java_org_boris_jvst_JNI_processReplacing
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jint);


}

#endif
