/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsjack;

public final class JackPortFlags {
  public final static int JackPortIsInput = mmsjackJNI.JackPortIsInput_get();
  public final static int JackPortIsOutput = mmsjackJNI.JackPortIsOutput_get();
  public final static int JackPortIsPhysical = mmsjackJNI.JackPortIsPhysical_get();
  public final static int JackPortCanMonitor = mmsjackJNI.JackPortCanMonitor_get();
  public final static int JackPortIsTerminal = mmsjackJNI.JackPortIsTerminal_get();
  public final static int JackPortIsActive = mmsjackJNI.JackPortIsActive_get();
}

