/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xtract.core;

public class xtract_function_descriptor_t_algo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected xtract_function_descriptor_t_algo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xtract_function_descriptor_t_algo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      xtractJNI.delete_xtract_function_descriptor_t_algo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(String value) {
    xtractJNI.xtract_function_descriptor_t_algo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return xtractJNI.xtract_function_descriptor_t_algo_name_get(swigCPtr, this);
  }

  public void setP_name(String value) {
    xtractJNI.xtract_function_descriptor_t_algo_p_name_set(swigCPtr, this, value);
  }

  public String getP_name() {
    return xtractJNI.xtract_function_descriptor_t_algo_p_name_get(swigCPtr, this);
  }

  public void setDesc(String value) {
    xtractJNI.xtract_function_descriptor_t_algo_desc_set(swigCPtr, this, value);
  }

  public String getDesc() {
    return xtractJNI.xtract_function_descriptor_t_algo_desc_get(swigCPtr, this);
  }

  public void setP_desc(String value) {
    xtractJNI.xtract_function_descriptor_t_algo_p_desc_set(swigCPtr, this, value);
  }

  public String getP_desc() {
    return xtractJNI.xtract_function_descriptor_t_algo_p_desc_get(swigCPtr, this);
  }

  public void setAuthor(String value) {
    xtractJNI.xtract_function_descriptor_t_algo_author_set(swigCPtr, this, value);
  }

  public String getAuthor() {
    return xtractJNI.xtract_function_descriptor_t_algo_author_get(swigCPtr, this);
  }

  public void setYear(int value) {
    xtractJNI.xtract_function_descriptor_t_algo_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return xtractJNI.xtract_function_descriptor_t_algo_year_get(swigCPtr, this);
  }

  public xtract_function_descriptor_t_algo() {
    this(xtractJNI.new_xtract_function_descriptor_t_algo(), true);
  }

}
