/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xtract.core;

public class xtract_function_descriptor_t_argv {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected xtract_function_descriptor_t_argv(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xtract_function_descriptor_t_argv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      xtractJNI.delete_xtract_function_descriptor_t_argv(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setType(xtract_type_t value) {
    xtractJNI.xtract_function_descriptor_t_argv_type_set(swigCPtr, this, value.swigValue());
  }

  public xtract_type_t getType() {
    return xtract_type_t.swigToEnum(xtractJNI.xtract_function_descriptor_t_argv_type_get(swigCPtr, this));
  }

  public void setMin(SWIGTYPE_p_float value) {
    xtractJNI.xtract_function_descriptor_t_argv_min_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getMin() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setMax(SWIGTYPE_p_float value) {
    xtractJNI.xtract_function_descriptor_t_argv_max_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getMax() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setDef(SWIGTYPE_p_float value) {
    xtractJNI.xtract_function_descriptor_t_argv_def_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getDef() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_def_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setUnit(SWIGTYPE_p_unit_ value) {
    xtractJNI.xtract_function_descriptor_t_argv_unit_set(swigCPtr, this, SWIGTYPE_p_unit_.getCPtr(value));
  }

  public SWIGTYPE_p_unit_ getUnit() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_unit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unit_(cPtr, false);
  }

  public void setDonor(SWIGTYPE_p_int value) {
    xtractJNI.xtract_function_descriptor_t_argv_donor_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getDonor() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_donor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public xtract_function_descriptor_t_argv() {
    this(xtractJNI.new_xtract_function_descriptor_t_argv(), true);
  }

}
