/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xtract.core;

public class xtract_function_descriptor_t_data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected xtract_function_descriptor_t_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xtract_function_descriptor_t_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      xtractJNI.delete_xtract_function_descriptor_t_data(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setFormat(xtract_vector_t value) {
    xtractJNI.xtract_function_descriptor_t_data_format_set(swigCPtr, this, value.swigValue());
  }

  public xtract_vector_t getFormat() {
    return xtract_vector_t.swigToEnum(xtractJNI.xtract_function_descriptor_t_data_format_get(swigCPtr, this));
  }

  public void setUnit(xtract_unit_t value) {
    xtractJNI.xtract_function_descriptor_t_data_unit_set(swigCPtr, this, value.swigValue());
  }

  public xtract_unit_t getUnit() {
    return xtract_unit_t.swigToEnum(xtractJNI.xtract_function_descriptor_t_data_unit_get(swigCPtr, this));
  }

  public xtract_function_descriptor_t_data() {
    this(xtractJNI.new_xtract_function_descriptor_t_data(), true);
  }

}
