/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsjack;

public final class JackOptions {
  public final static int JackNullOption = mmsjackJNI.JackNullOption_get();
  public final static int JackNoStartServer = mmsjackJNI.JackNoStartServer_get();
  public final static int JackUseExactName = mmsjackJNI.JackUseExactName_get();
  public final static int JackServerName = mmsjackJNI.JackServerName_get();
  public final static int JackLoadName = mmsjackJNI.JackLoadName_get();
  public final static int JackLoadInit = mmsjackJNI.JackLoadInit_get();
}

