/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsjack;

public interface mmsjackConstants {
  public final static String JACK_DEFAULT_AUDIO_TYPE = mmsjackJNI.JACK_DEFAULT_AUDIO_TYPE_get();
  public final static String JACK_DEFAULT_MIDI_TYPE = mmsjackJNI.JACK_DEFAULT_MIDI_TYPE_get();
}
