/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC)
#   if (__SUNPRO_CC <= 0x560)
#     define SWIGTEMPLATEDISAMBIGUATOR template
#   else
#     define SWIGTEMPLATEDISAMBIGUATOR 
#   endif
# else
#   define SWIGTEMPLATEDISAMBIGUATOR 
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTELC__)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaException,
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
	{ SWIG_JavaException, "java/lang/Exception" },
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

#include "portaudio.h"

typedef struct {
    long 			stream;
	JNIEnv * 		env;
	jclass 			cls;
	jmethodID 		mid;
    jobject 		obj_callback;
	int 			attached;
    int 			input_frame_size;
	int 			output_frame_size;
	PaSampleFormat 	input_sampleFormat;
	PaSampleFormat 	output_sampleFormat;
	int 			numInputChannels;
	int				numOutputChannels;
	double 			sampleRate;
	unsigned long 	framesPerBuffer;
} UserData;

JavaVM * virtual_machine;

int callback(const void * input, void * output, unsigned long frame_count, const PaStreamCallbackTimeInfo * time_info, PaStreamCallbackFlags status_flags, void * user_data) {
	int ret;
	jobject input_buffer = NULL;
	jobject output_buffer = NULL;
		
	UserData * data = (UserData *) user_data;
	if (data == NULL) {
		printf("portaudio: there is no user data...\n"); fflush(stdout);
	}

	if (data->attached == 0) {
		data->attached = 1;
		(*virtual_machine)->AttachCurrentThreadAsDaemon(virtual_machine, (void **) &data->env, NULL);
		data->cls = (*data->env)->FindClass(data->env, "mmsportaudio/PaCallback");
		data->mid = (*data->env)->GetMethodID(data->env, data->cls, "callback", "(JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JDDD)I");
	}

	ret = (int)(*data->env)->CallIntMethod(data->env, data->obj_callback, data->mid,
								(jlong) data->stream,
								input_buffer = (*data->env)->NewDirectByteBuffer(data->env, (void *) input, (jint) frame_count * data->input_frame_size),
								output_buffer = (*data->env)->NewDirectByteBuffer(data->env, output, (jint) frame_count * data->output_frame_size),
								(jlong)frame_count,
								(jdouble)time_info->inputBufferAdcTime,
								(jdouble)time_info->currentTime,
								(jdouble)time_info->outputBufferDacTime
					);

	return ret;
}

void hook(void * user_data) {
	UserData * data = (UserData *) user_data;
	(*data->env)->CallVoidMethod(data->env, data->obj_callback, (*data->env)->GetMethodID(data->env, data->cls, "hook", "(J)V"), data->stream);
	(*data->env)->DeleteGlobalRef(data->env, data->obj_callback);
	free(data);
}

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1structVersion_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->structVersion = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1structVersion_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result = (int) ((arg1)->structVersion);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaHostApiTypeId arg2 ;
  PaHostApiTypeId *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  argp2 = *(PaHostApiTypeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null PaHostApiTypeId");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->type = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaHostApiTypeId result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result =  ((arg1)->type);
  {
    PaHostApiTypeId * resultptr = (PaHostApiTypeId *) malloc(sizeof(PaHostApiTypeId));
    memmove(resultptr, &result, sizeof(PaHostApiTypeId));
    *(PaHostApiTypeId **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->name) free((char *)arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result = (char *) ((arg1)->name);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1deviceCount_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->deviceCount = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1deviceCount_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result = (int) ((arg1)->deviceCount);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1defaultInputDevice_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaDeviceIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  arg2 = (PaDeviceIndex)jarg2; 
  if (arg1) (arg1)->defaultInputDevice = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1defaultInputDevice_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result = (PaDeviceIndex) ((arg1)->defaultInputDevice);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1defaultOutputDevice_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaDeviceIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  arg2 = (PaDeviceIndex)jarg2; 
  if (arg1) (arg1)->defaultOutputDevice = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaHostApiInfo_1defaultOutputDevice_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  result = (PaDeviceIndex) ((arg1)->defaultOutputDevice);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaHostApiInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaHostApiInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaHostApiInfo *)(PaHostApiInfo *) calloc(1, sizeof(PaHostApiInfo));
  *(PaHostApiInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaHostApiInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaHostApiInfo *arg1 = (PaHostApiInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaHostApiInfo **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1hostApiType_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  PaHostApiTypeId arg2 ;
  PaHostApiTypeId *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  argp2 = *(PaHostApiTypeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null PaHostApiTypeId");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->hostApiType = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1hostApiType_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  PaHostApiTypeId result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  result =  ((arg1)->hostApiType);
  {
    PaHostApiTypeId * resultptr = (PaHostApiTypeId *) malloc(sizeof(PaHostApiTypeId));
    memmove(resultptr, &result, sizeof(PaHostApiTypeId));
    *(PaHostApiTypeId **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1errorCode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->errorCode = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1errorCode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  result = (long) ((arg1)->errorCode);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1errorText_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->errorText) free((char *)arg1->errorText);
    if (arg2) {
      arg1->errorText = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->errorText, (const char *)arg2);
    } else {
      arg1->errorText = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_mmsportaudio_portaudioJNI_PaHostErrorInfo_1errorText_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  result = (char *) ((arg1)->errorText);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaHostErrorInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaHostErrorInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaHostErrorInfo *)(PaHostErrorInfo *) calloc(1, sizeof(PaHostErrorInfo));
  *(PaHostErrorInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaHostErrorInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaHostErrorInfo *arg1 = (PaHostErrorInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaHostErrorInfo **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1structVersion_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->structVersion = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1structVersion_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (int) ((arg1)->structVersion);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->name) free((char *)arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (char *) ((arg1)->name);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1hostApi_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaHostApiIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (PaHostApiIndex)jarg2; 
  if (arg1) (arg1)->hostApi = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1hostApi_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaHostApiIndex result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (PaHostApiIndex) ((arg1)->hostApi);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1maxInputChannels_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->maxInputChannels = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1maxInputChannels_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (int) ((arg1)->maxInputChannels);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1maxOutputChannels_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->maxOutputChannels = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1maxOutputChannels_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (int) ((arg1)->maxOutputChannels);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultLowInputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->defaultLowInputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultLowInputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (PaTime) ((arg1)->defaultLowInputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultLowOutputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->defaultLowOutputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultLowOutputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (PaTime) ((arg1)->defaultLowOutputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultHighInputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->defaultHighInputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultHighInputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (PaTime) ((arg1)->defaultHighInputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultHighOutputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->defaultHighOutputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultHighOutputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (PaTime) ((arg1)->defaultHighOutputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultSampleRate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->defaultSampleRate = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaDeviceInfo_1defaultSampleRate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  result = (double) ((arg1)->defaultSampleRate);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaDeviceInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaDeviceInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaDeviceInfo *)(PaDeviceInfo *) calloc(1, sizeof(PaDeviceInfo));
  *(PaDeviceInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaDeviceInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaDeviceInfo *arg1 = (PaDeviceInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaDeviceInfo **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1device_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaDeviceIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = (PaDeviceIndex)jarg2; 
  if (arg1) (arg1)->device = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1device_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  result = (PaDeviceIndex) ((arg1)->device);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1channelCount_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->channelCount = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1channelCount_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  result = (int) ((arg1)->channelCount);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1sampleFormat_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaSampleFormat arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = (PaSampleFormat)jarg2; 
  if (arg1) (arg1)->sampleFormat = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1sampleFormat_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaSampleFormat result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  result = (PaSampleFormat) ((arg1)->sampleFormat);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1suggestedLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->suggestedLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1suggestedLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  result = (PaTime) ((arg1)->suggestedLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1hostApiSpecificStreamInfo_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->hostApiSpecificStreamInfo = arg2;
  
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_PaStreamParameters_1hostApiSpecificStreamInfo_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  result = (void *) ((arg1)->hostApiSpecificStreamInfo);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaStreamParameters(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaStreamParameters *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaStreamParameters *)(PaStreamParameters *) calloc(1, sizeof(PaStreamParameters));
  *(PaStreamParameters **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaStreamParameters(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStreamParameters **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1inputBufferAdcTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->inputBufferAdcTime = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1inputBufferAdcTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  result = (PaTime) ((arg1)->inputBufferAdcTime);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1currentTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->currentTime = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1currentTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  result = (PaTime) ((arg1)->currentTime);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1outputBufferDacTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->outputBufferDacTime = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamCallbackTimeInfo_1outputBufferDacTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  result = (PaTime) ((arg1)->outputBufferDacTime);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaStreamCallbackTimeInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaStreamCallbackTimeInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaStreamCallbackTimeInfo *)(PaStreamCallbackTimeInfo *) calloc(1, sizeof(PaStreamCallbackTimeInfo));
  *(PaStreamCallbackTimeInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaStreamCallbackTimeInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaStreamCallbackTimeInfo *arg1 = (PaStreamCallbackTimeInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStreamCallbackTimeInfo **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1structVersion_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->structVersion = arg2;
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1structVersion_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  result = (int) ((arg1)->structVersion);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1inputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->inputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1inputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  result = (PaTime) ((arg1)->inputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1outputLatency_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  PaTime arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  arg2 = (PaTime)jarg2; 
  if (arg1) (arg1)->outputLatency = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1outputLatency_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  result = (PaTime) ((arg1)->outputLatency);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1sampleRate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->sampleRate = arg2;
  
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_PaStreamInfo_1sampleRate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PaStreamInfo **)&jarg1; 
  result = (double) ((arg1)->sampleRate);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_new_1PaStreamInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaStreamInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaStreamInfo *)(PaStreamInfo *) calloc(1, sizeof(PaStreamInfo));
  *(PaStreamInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_delete_1PaStreamInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PaStreamInfo *arg1 = (PaStreamInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStreamInfo **)&jarg1; 
  free((char *) arg1);
  
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetVersion(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)Pa_GetVersion();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetVersionText(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)Pa_GetVersionText();
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetErrorText(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jstring jresult = 0 ;
  PaError arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PaError)jarg1; 
  result = (char *)Pa_GetErrorText(arg1);
  if(result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1Initialize(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;

  // Leandro - BEGIN
  (*jenv)->GetJavaVM(jenv, &virtual_machine);
  result = (PaError)Pa_Initialize();
  if (result != paNoError) {
    SWIG_JavaThrowException(jenv, SWIG_JavaException, Pa_GetErrorText(result));
  }
  // Leandro - END

  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1Terminate(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  result = (PaError)Pa_Terminate();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetHostApiCount(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaHostApiIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (PaHostApiIndex)Pa_GetHostApiCount();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetDefaultHostApi(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaHostApiIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (PaHostApiIndex)Pa_GetDefaultHostApi();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetHostApiInfo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  PaHostApiIndex arg1 ;
  PaHostApiInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PaHostApiIndex)jarg1; 
  result = (PaHostApiInfo *)Pa_GetHostApiInfo(arg1);
  *(PaHostApiInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1HostApiTypeIdToHostApiIndex(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaHostApiTypeId arg1 ;
  PaHostApiIndex result;
  PaHostApiTypeId *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(PaHostApiTypeId **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null PaHostApiTypeId");
    return 0;
  }
  arg1 = *argp1; 
  result = (PaHostApiIndex)Pa_HostApiTypeIdToHostApiIndex(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1HostApiDeviceIndexToDeviceIndex(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  PaHostApiIndex arg1 ;
  int arg2 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PaHostApiIndex)jarg1; 
  arg2 = (int)jarg2; 
  result = (PaDeviceIndex)Pa_HostApiDeviceIndexToDeviceIndex(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetLastHostErrorInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PaHostErrorInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PaHostErrorInfo *)Pa_GetLastHostErrorInfo();
  *(PaHostErrorInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetDeviceCount(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (PaDeviceIndex)Pa_GetDeviceCount();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetDefaultInputDevice(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (PaDeviceIndex)Pa_GetDefaultInputDevice();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetDefaultOutputDevice(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  PaDeviceIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (PaDeviceIndex)Pa_GetDefaultOutputDevice();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetDeviceInfo(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  PaDeviceIndex arg1 ;
  PaDeviceInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PaDeviceIndex)jarg1; 
  result = (PaDeviceInfo *)Pa_GetDeviceInfo(arg1);
  *(PaDeviceInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1IsFormatSupported(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3) {
  jint jresult = 0 ;
  PaStreamParameters *arg1 = (PaStreamParameters *) 0 ;
  PaStreamParameters *arg2 = (PaStreamParameters *) 0 ;
  double arg3 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PaStreamParameters **)&jarg1; 
  arg2 = *(PaStreamParameters **)&jarg2; 
  arg3 = (double)jarg3; 
  result = (PaError)Pa_IsFormatSupported(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1OpenStream(JNIEnv *jenv, jclass jcls, jlong jarg2, jobject jarg2_, jlong jarg3, jobject jarg3_, jdouble jarg4, jlong jarg5, jlong jarg6, jobject jarg7) {
	UserData * data;
	PaError error;
	PaStream * stream;
  
  jint jresult = 0 ;
  PaStreamParameters *arg2 = (PaStreamParameters *) 0 ;
  PaStreamParameters *arg3 = (PaStreamParameters *) 0 ;
  double arg4 ;
  unsigned long arg5 ;
  PaStreamFlags arg6 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  (void)jarg3_;
  arg2 = *(PaStreamParameters **)&jarg2; 
  arg3 = *(PaStreamParameters **)&jarg3; 
  arg4 = (double)jarg4; 
  arg5 = (unsigned long)jarg5; 
  arg6 = (PaStreamFlags)jarg6; 

	// Leandro - BEGIN

  	// Creates userData and set parameters
	data = (UserData *)malloc(sizeof(UserData));
	data->attached = 0;
	data->obj_callback = (*jenv)->NewGlobalRef(jenv, jarg7);
	if (arg2 != NULL) {
		data->numInputChannels = arg2->channelCount;
		data->input_sampleFormat = arg2->sampleFormat;
	} else {
		data->numInputChannels = 0;
	}
	if (arg3 != NULL) {
		data->numOutputChannels = arg3->channelCount;
		data->output_sampleFormat = arg3->sampleFormat;
	} else {
		data->numOutputChannels = 0;
	}
	data->sampleRate = arg4;
	data->framesPerBuffer = arg5;
	data->input_frame_size = Pa_GetSampleSize(data->input_sampleFormat) * data->numInputChannels;
	data->output_frame_size = Pa_GetSampleSize(data->output_sampleFormat) * data->numOutputChannels;

  	// Opens the stream
	error = (PaError)Pa_OpenStream(&stream,arg2,arg3,arg4,arg5,arg6,callback,data);
	data->stream = (long) stream;
//	printf("OpenStream = %ld\n", data->stream);fflush(stdout);
//	printf("error = %d - %s\n", error, Pa_GetErrorText(error)); fflush(stdout);
	error = Pa_SetStreamFinishedCallback(stream, hook);

	return stream;
	// Leandro - END
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1OpenDefaultStream(JNIEnv *jenv, jclass jcls, jint jarg2, jint jarg3, jlong jarg4, jdouble jarg5, jlong jarg6, jobject jarg7) {
	UserData * data;
	PaError error;
	PaStream * stream;

  jint jresult = 0 ;
  int arg2 ;
  int arg3 ;
  PaSampleFormat arg4 ;
  double arg5 ;
  unsigned long arg6 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PaSampleFormat)jarg4; 
  arg5 = (double)jarg5; 
  arg6 = (unsigned long)jarg6; 

  // Leandro - BEGIN

  // Creates userData and set parameters
	data = (UserData *)malloc(sizeof(UserData));
	data->attached = 0;
  	data->obj_callback = (*jenv)->NewGlobalRef(jenv, jarg7);
	data->numInputChannels = arg2;
	data->numOutputChannels = arg3;
	data->input_sampleFormat = arg4;
	data->output_sampleFormat = arg4;
	data->sampleRate = arg5;
	data->framesPerBuffer = arg6;
	data->input_frame_size = Pa_GetSampleSize(data->input_sampleFormat) * data->numInputChannels;
	data->output_frame_size = Pa_GetSampleSize(data->output_sampleFormat) * data->numOutputChannels;

  // Opens the stream
	error = (PaError)Pa_OpenDefaultStream(&stream,arg2,arg3,arg4,arg5,arg6,callback,data);
	error = Pa_SetStreamFinishedCallback(stream, hook);
	data->stream = (long) stream;
//	printf("OpenDefaultStream = %ld\n", data->stream);fflush(stdout);

  // Leandro - END

  return stream;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1CloseStream(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  (void)jenv;
  (void)jcls;
//  arg1 = *(PaStream **)&jarg1;
//  printf("CloseStream = %d\n", jarg1);fflush(stdout);
  result = (PaError)Pa_CloseStream((PaStream *)jarg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1SetStreamFinishedCallback(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaStreamFinishedCallback *arg2 = (PaStreamFinishedCallback *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  arg2 = *(PaStreamFinishedCallback **)&jarg2; 
  result = (PaError)Pa_SetStreamFinishedCallback(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1StartStream(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1;
  result = (PaError)Pa_StartStream(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1StopStream(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1;
  result = (PaError)Pa_StopStream(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1AbortStream(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (PaError)Pa_AbortStream(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1IsStreamStopped(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (PaError)Pa_IsStreamStopped(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1IsStreamActive(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (PaError)Pa_IsStreamActive(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetStreamInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaStreamInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (PaStreamInfo *)Pa_GetStreamInfo(arg1);
  *(PaStreamInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetStreamTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  PaTime result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (PaTime)Pa_GetStreamTime(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetStreamCpuLoad(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (double)Pa_GetStreamCpuLoad(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1ReadStream(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  void *arg2 = (void *) 0 ;
  unsigned long arg3 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (unsigned long)jarg3; 
  result = (PaError)Pa_ReadStream(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1WriteStream(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  void *arg2 = (void *) 0 ;
  unsigned long arg3 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (unsigned long)jarg3; 
  result = (PaError)Pa_WriteStream(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetStreamReadAvailable(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (long)Pa_GetStreamReadAvailable(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetStreamWriteAvailable(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaStream *arg1 = (PaStream *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PaStream **)&jarg1; 
  result = (long)Pa_GetStreamWriteAvailable(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_mmsportaudio_portaudioJNI_Pa_1GetSampleSize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PaSampleFormat arg1 ;
  PaError result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PaSampleFormat)jarg1; 
  result = (PaError)Pa_GetSampleSize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mmsportaudio_portaudioJNI_Pa_1Sleep(JNIEnv *jenv, jclass jcls, jint jarg1) {
  long arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (long)jarg1; 
  Pa_Sleep(arg1);
}


#ifdef __cplusplus
}
#endif
