/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

public class PaDeviceInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PaDeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PaDeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      portaudioJNI.delete_PaDeviceInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStructVersion(int value) {
    portaudioJNI.PaDeviceInfo_structVersion_set(swigCPtr, this, value);
  }

  public int getStructVersion() {
    return portaudioJNI.PaDeviceInfo_structVersion_get(swigCPtr, this);
  }

  public void setName(String value) {
    portaudioJNI.PaDeviceInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return portaudioJNI.PaDeviceInfo_name_get(swigCPtr, this);
  }

  public void setHostApi(int value) {
    portaudioJNI.PaDeviceInfo_hostApi_set(swigCPtr, this, value);
  }

  public int getHostApi() {
    return portaudioJNI.PaDeviceInfo_hostApi_get(swigCPtr, this);
  }

  public void setMaxInputChannels(int value) {
    portaudioJNI.PaDeviceInfo_maxInputChannels_set(swigCPtr, this, value);
  }

  public int getMaxInputChannels() {
    return portaudioJNI.PaDeviceInfo_maxInputChannels_get(swigCPtr, this);
  }

  public void setMaxOutputChannels(int value) {
    portaudioJNI.PaDeviceInfo_maxOutputChannels_set(swigCPtr, this, value);
  }

  public int getMaxOutputChannels() {
    return portaudioJNI.PaDeviceInfo_maxOutputChannels_get(swigCPtr, this);
  }

  public void setDefaultLowInputLatency(double value) {
    portaudioJNI.PaDeviceInfo_defaultLowInputLatency_set(swigCPtr, this, value);
  }

  public double getDefaultLowInputLatency() {
    return portaudioJNI.PaDeviceInfo_defaultLowInputLatency_get(swigCPtr, this);
  }

  public void setDefaultLowOutputLatency(double value) {
    portaudioJNI.PaDeviceInfo_defaultLowOutputLatency_set(swigCPtr, this, value);
  }

  public double getDefaultLowOutputLatency() {
    return portaudioJNI.PaDeviceInfo_defaultLowOutputLatency_get(swigCPtr, this);
  }

  public void setDefaultHighInputLatency(double value) {
    portaudioJNI.PaDeviceInfo_defaultHighInputLatency_set(swigCPtr, this, value);
  }

  public double getDefaultHighInputLatency() {
    return portaudioJNI.PaDeviceInfo_defaultHighInputLatency_get(swigCPtr, this);
  }

  public void setDefaultHighOutputLatency(double value) {
    portaudioJNI.PaDeviceInfo_defaultHighOutputLatency_set(swigCPtr, this, value);
  }

  public double getDefaultHighOutputLatency() {
    return portaudioJNI.PaDeviceInfo_defaultHighOutputLatency_get(swigCPtr, this);
  }

  public void setDefaultSampleRate(double value) {
    portaudioJNI.PaDeviceInfo_defaultSampleRate_set(swigCPtr, this, value);
  }

  public double getDefaultSampleRate() {
    return portaudioJNI.PaDeviceInfo_defaultSampleRate_get(swigCPtr, this);
  }

  public PaDeviceInfo() {
    this(portaudioJNI.new_PaDeviceInfo(), true);
  }

}
