/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

public class PaHostApiInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PaHostApiInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PaHostApiInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      portaudioJNI.delete_PaHostApiInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStructVersion(int value) {
    portaudioJNI.PaHostApiInfo_structVersion_set(swigCPtr, this, value);
  }

  public int getStructVersion() {
    return portaudioJNI.PaHostApiInfo_structVersion_get(swigCPtr, this);
  }

  public void setType(SWIGTYPE_p_PaHostApiTypeId value) {
    portaudioJNI.PaHostApiInfo_type_set(swigCPtr, this, SWIGTYPE_p_PaHostApiTypeId.getCPtr(value));
  }

  public SWIGTYPE_p_PaHostApiTypeId getType() {
    return new SWIGTYPE_p_PaHostApiTypeId(portaudioJNI.PaHostApiInfo_type_get(swigCPtr, this), true);
  }

  public void setName(String value) {
    portaudioJNI.PaHostApiInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return portaudioJNI.PaHostApiInfo_name_get(swigCPtr, this);
  }

  public void setDeviceCount(int value) {
    portaudioJNI.PaHostApiInfo_deviceCount_set(swigCPtr, this, value);
  }

  public int getDeviceCount() {
    return portaudioJNI.PaHostApiInfo_deviceCount_get(swigCPtr, this);
  }

  public void setDefaultInputDevice(int value) {
    portaudioJNI.PaHostApiInfo_defaultInputDevice_set(swigCPtr, this, value);
  }

  public int getDefaultInputDevice() {
    return portaudioJNI.PaHostApiInfo_defaultInputDevice_get(swigCPtr, this);
  }

  public void setDefaultOutputDevice(int value) {
    portaudioJNI.PaHostApiInfo_defaultOutputDevice_set(swigCPtr, this, value);
  }

  public int getDefaultOutputDevice() {
    return portaudioJNI.PaHostApiInfo_defaultOutputDevice_get(swigCPtr, this);
  }

  public PaHostApiInfo() {
    this(portaudioJNI.new_PaHostApiInfo(), true);
  }

}
