/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

public class PaHostErrorInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PaHostErrorInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PaHostErrorInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      portaudioJNI.delete_PaHostErrorInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setHostApiType(SWIGTYPE_p_PaHostApiTypeId value) {
    portaudioJNI.PaHostErrorInfo_hostApiType_set(swigCPtr, this, SWIGTYPE_p_PaHostApiTypeId.getCPtr(value));
  }

  public SWIGTYPE_p_PaHostApiTypeId getHostApiType() {
    return new SWIGTYPE_p_PaHostApiTypeId(portaudioJNI.PaHostErrorInfo_hostApiType_get(swigCPtr, this), true);
  }

  public void setErrorCode(int value) {
    portaudioJNI.PaHostErrorInfo_errorCode_set(swigCPtr, this, value);
  }

  public int getErrorCode() {
    return portaudioJNI.PaHostErrorInfo_errorCode_get(swigCPtr, this);
  }

  public void setErrorText(String value) {
    portaudioJNI.PaHostErrorInfo_errorText_set(swigCPtr, this, value);
  }

  public String getErrorText() {
    return portaudioJNI.PaHostErrorInfo_errorText_get(swigCPtr, this);
  }

  public PaHostErrorInfo() {
    this(portaudioJNI.new_PaHostErrorInfo(), true);
  }

}
