/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

public class PaStreamParameters {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PaStreamParameters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PaStreamParameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      portaudioJNI.delete_PaStreamParameters(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setDevice(int value) {
    portaudioJNI.PaStreamParameters_device_set(swigCPtr, this, value);
  }

  public int getDevice() {
    return portaudioJNI.PaStreamParameters_device_get(swigCPtr, this);
  }

  public void setChannelCount(int value) {
    portaudioJNI.PaStreamParameters_channelCount_set(swigCPtr, this, value);
  }

  public int getChannelCount() {
    return portaudioJNI.PaStreamParameters_channelCount_get(swigCPtr, this);
  }

  public void setSampleFormat(long value) {
    portaudioJNI.PaStreamParameters_sampleFormat_set(swigCPtr, this, value);
  }

  public long getSampleFormat() {
    return portaudioJNI.PaStreamParameters_sampleFormat_get(swigCPtr, this);
  }

  public void setSuggestedLatency(double value) {
    portaudioJNI.PaStreamParameters_suggestedLatency_set(swigCPtr, this, value);
  }

  public double getSuggestedLatency() {
    return portaudioJNI.PaStreamParameters_suggestedLatency_get(swigCPtr, this);
  }

  public void setHostApiSpecificStreamInfo(SWIGTYPE_p_void value) {
    portaudioJNI.PaStreamParameters_hostApiSpecificStreamInfo_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getHostApiSpecificStreamInfo() {
    long cPtr = portaudioJNI.PaStreamParameters_hostApiSpecificStreamInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public PaStreamParameters() {
    this(portaudioJNI.new_PaStreamParameters(), true);
  }

}
