/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

public class PaStreamCallbackTimeInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PaStreamCallbackTimeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PaStreamCallbackTimeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      portaudioJNI.delete_PaStreamCallbackTimeInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setInputBufferAdcTime(double value) {
    portaudioJNI.PaStreamCallbackTimeInfo_inputBufferAdcTime_set(swigCPtr, this, value);
  }

  public double getInputBufferAdcTime() {
    return portaudioJNI.PaStreamCallbackTimeInfo_inputBufferAdcTime_get(swigCPtr, this);
  }

  public void setCurrentTime(double value) {
    portaudioJNI.PaStreamCallbackTimeInfo_currentTime_set(swigCPtr, this, value);
  }

  public double getCurrentTime() {
    return portaudioJNI.PaStreamCallbackTimeInfo_currentTime_get(swigCPtr, this);
  }

  public void setOutputBufferDacTime(double value) {
    portaudioJNI.PaStreamCallbackTimeInfo_outputBufferDacTime_set(swigCPtr, this, value);
  }

  public double getOutputBufferDacTime() {
    return portaudioJNI.PaStreamCallbackTimeInfo_outputBufferDacTime_get(swigCPtr, this);
  }

  public PaStreamCallbackTimeInfo() {
    this(portaudioJNI.new_PaStreamCallbackTimeInfo(), true);
  }

}
