/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmsportaudio;

class portaudioJNI {
  public final static native void PaHostApiInfo_structVersion_set(long jarg1, PaHostApiInfo jarg1_, int jarg2);
  public final static native int PaHostApiInfo_structVersion_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native void PaHostApiInfo_type_set(long jarg1, PaHostApiInfo jarg1_, long jarg2);
  public final static native long PaHostApiInfo_type_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native void PaHostApiInfo_name_set(long jarg1, PaHostApiInfo jarg1_, String jarg2);
  public final static native String PaHostApiInfo_name_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native void PaHostApiInfo_deviceCount_set(long jarg1, PaHostApiInfo jarg1_, int jarg2);
  public final static native int PaHostApiInfo_deviceCount_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native void PaHostApiInfo_defaultInputDevice_set(long jarg1, PaHostApiInfo jarg1_, int jarg2);
  public final static native int PaHostApiInfo_defaultInputDevice_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native void PaHostApiInfo_defaultOutputDevice_set(long jarg1, PaHostApiInfo jarg1_, int jarg2);
  public final static native int PaHostApiInfo_defaultOutputDevice_get(long jarg1, PaHostApiInfo jarg1_);
  public final static native long new_PaHostApiInfo();
  public final static native void delete_PaHostApiInfo(long jarg1);
  public final static native void PaHostErrorInfo_hostApiType_set(long jarg1, PaHostErrorInfo jarg1_, long jarg2);
  public final static native long PaHostErrorInfo_hostApiType_get(long jarg1, PaHostErrorInfo jarg1_);
  public final static native void PaHostErrorInfo_errorCode_set(long jarg1, PaHostErrorInfo jarg1_, int jarg2);
  public final static native int PaHostErrorInfo_errorCode_get(long jarg1, PaHostErrorInfo jarg1_);
  public final static native void PaHostErrorInfo_errorText_set(long jarg1, PaHostErrorInfo jarg1_, String jarg2);
  public final static native String PaHostErrorInfo_errorText_get(long jarg1, PaHostErrorInfo jarg1_);
  public final static native long new_PaHostErrorInfo();
  public final static native void delete_PaHostErrorInfo(long jarg1);
  public final static native void PaDeviceInfo_structVersion_set(long jarg1, PaDeviceInfo jarg1_, int jarg2);
  public final static native int PaDeviceInfo_structVersion_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_name_set(long jarg1, PaDeviceInfo jarg1_, String jarg2);
  public final static native String PaDeviceInfo_name_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_hostApi_set(long jarg1, PaDeviceInfo jarg1_, int jarg2);
  public final static native int PaDeviceInfo_hostApi_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_maxInputChannels_set(long jarg1, PaDeviceInfo jarg1_, int jarg2);
  public final static native int PaDeviceInfo_maxInputChannels_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_maxOutputChannels_set(long jarg1, PaDeviceInfo jarg1_, int jarg2);
  public final static native int PaDeviceInfo_maxOutputChannels_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_defaultLowInputLatency_set(long jarg1, PaDeviceInfo jarg1_, double jarg2);
  public final static native double PaDeviceInfo_defaultLowInputLatency_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_defaultLowOutputLatency_set(long jarg1, PaDeviceInfo jarg1_, double jarg2);
  public final static native double PaDeviceInfo_defaultLowOutputLatency_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_defaultHighInputLatency_set(long jarg1, PaDeviceInfo jarg1_, double jarg2);
  public final static native double PaDeviceInfo_defaultHighInputLatency_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_defaultHighOutputLatency_set(long jarg1, PaDeviceInfo jarg1_, double jarg2);
  public final static native double PaDeviceInfo_defaultHighOutputLatency_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native void PaDeviceInfo_defaultSampleRate_set(long jarg1, PaDeviceInfo jarg1_, double jarg2);
  public final static native double PaDeviceInfo_defaultSampleRate_get(long jarg1, PaDeviceInfo jarg1_);
  public final static native long new_PaDeviceInfo();
  public final static native void delete_PaDeviceInfo(long jarg1);
  public final static native void PaStreamParameters_device_set(long jarg1, PaStreamParameters jarg1_, int jarg2);
  public final static native int PaStreamParameters_device_get(long jarg1, PaStreamParameters jarg1_);
  public final static native void PaStreamParameters_channelCount_set(long jarg1, PaStreamParameters jarg1_, int jarg2);
  public final static native int PaStreamParameters_channelCount_get(long jarg1, PaStreamParameters jarg1_);
  public final static native void PaStreamParameters_sampleFormat_set(long jarg1, PaStreamParameters jarg1_, long jarg2);
  public final static native long PaStreamParameters_sampleFormat_get(long jarg1, PaStreamParameters jarg1_);
  public final static native void PaStreamParameters_suggestedLatency_set(long jarg1, PaStreamParameters jarg1_, double jarg2);
  public final static native double PaStreamParameters_suggestedLatency_get(long jarg1, PaStreamParameters jarg1_);
  public final static native void PaStreamParameters_hostApiSpecificStreamInfo_set(long jarg1, PaStreamParameters jarg1_, long jarg2);
  public final static native long PaStreamParameters_hostApiSpecificStreamInfo_get(long jarg1, PaStreamParameters jarg1_);
  public final static native long new_PaStreamParameters();
  public final static native void delete_PaStreamParameters(long jarg1);
  public final static native void PaStreamCallbackTimeInfo_inputBufferAdcTime_set(long jarg1, PaStreamCallbackTimeInfo jarg1_, double jarg2);
  public final static native double PaStreamCallbackTimeInfo_inputBufferAdcTime_get(long jarg1, PaStreamCallbackTimeInfo jarg1_);
  public final static native void PaStreamCallbackTimeInfo_currentTime_set(long jarg1, PaStreamCallbackTimeInfo jarg1_, double jarg2);
  public final static native double PaStreamCallbackTimeInfo_currentTime_get(long jarg1, PaStreamCallbackTimeInfo jarg1_);
  public final static native void PaStreamCallbackTimeInfo_outputBufferDacTime_set(long jarg1, PaStreamCallbackTimeInfo jarg1_, double jarg2);
  public final static native double PaStreamCallbackTimeInfo_outputBufferDacTime_get(long jarg1, PaStreamCallbackTimeInfo jarg1_);
  public final static native long new_PaStreamCallbackTimeInfo();
  public final static native void delete_PaStreamCallbackTimeInfo(long jarg1);
  public final static native void PaStreamInfo_structVersion_set(long jarg1, PaStreamInfo jarg1_, int jarg2);
  public final static native int PaStreamInfo_structVersion_get(long jarg1, PaStreamInfo jarg1_);
  public final static native void PaStreamInfo_inputLatency_set(long jarg1, PaStreamInfo jarg1_, double jarg2);
  public final static native double PaStreamInfo_inputLatency_get(long jarg1, PaStreamInfo jarg1_);
  public final static native void PaStreamInfo_outputLatency_set(long jarg1, PaStreamInfo jarg1_, double jarg2);
  public final static native double PaStreamInfo_outputLatency_get(long jarg1, PaStreamInfo jarg1_);
  public final static native void PaStreamInfo_sampleRate_set(long jarg1, PaStreamInfo jarg1_, double jarg2);
  public final static native double PaStreamInfo_sampleRate_get(long jarg1, PaStreamInfo jarg1_);
  public final static native long new_PaStreamInfo();
  public final static native void delete_PaStreamInfo(long jarg1);
  public final static native int Pa_GetVersion();
  public final static native String Pa_GetVersionText();
  public final static native String Pa_GetErrorText(int jarg1);
  public final static native int Pa_Initialize();
  public final static native int Pa_Terminate();
  public final static native int Pa_GetHostApiCount();
  public final static native int Pa_GetDefaultHostApi();
  public final static native long Pa_GetHostApiInfo(int jarg1);
  public final static native int Pa_HostApiTypeIdToHostApiIndex(long jarg1);
  public final static native int Pa_HostApiDeviceIndexToDeviceIndex(int jarg1, int jarg2);
  public final static native long Pa_GetLastHostErrorInfo();
  public final static native int Pa_GetDeviceCount();
  public final static native int Pa_GetDefaultInputDevice();
  public final static native int Pa_GetDefaultOutputDevice();
  public final static native long Pa_GetDeviceInfo(int jarg1);
  public final static native int Pa_IsFormatSupported(long jarg1, PaStreamParameters jarg1_, long jarg2, PaStreamParameters jarg2_, double jarg3);
  public final static native long Pa_OpenStream(long jarg1, PaStreamParameters jarg1_, long jarg2, PaStreamParameters jarg2_, double jarg3, long jarg4, long jarg5, Object jarg6);
  public final static native long Pa_OpenDefaultStream(int jarg1, int jarg2, long jarg3, double jarg4, long jarg5, Object jarg6);
  public final static native int Pa_CloseStream(long jarg1);
  public final static native int Pa_StartStream(long jarg1);
  public final static native int Pa_StopStream(long jarg1);
  public final static native int Pa_AbortStream(long jarg1);
  public final static native int Pa_IsStreamStopped(long jarg1);
  public final static native int Pa_IsStreamActive(long jarg1);
  public final static native long Pa_GetStreamInfo(long jarg1);
  public final static native double Pa_GetStreamTime(long jarg1);
  public final static native double Pa_GetStreamCpuLoad(long jarg1);
  public final static native int Pa_ReadStream(long jarg1, long jarg2, long jarg3);
  public final static native int Pa_WriteStream(long jarg1, long jarg2, long jarg3);
  public final static native int Pa_GetStreamReadAvailable(long jarg1);
  public final static native int Pa_GetStreamWriteAvailable(long jarg1);
  public final static native int Pa_GetSampleSize(long jarg1);
  public final static native void Pa_Sleep(int jarg1);
}
