STDC_HEADERS=STDC_HEADERS => 1
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
NDEBUG=NDEBUG => 1
TARGET_CPU_X86_64=TARGET_CPU_X86_64 => 1
__i386__=__i386__ => 1
_WCHAR_T_DEFINED=_WCHAR_T_DEFINED => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
__amd64__=__amd64__ => 1
_SoundTouchDLL_h_=_SoundTouchDLL_h_
_MSC_VER=_MSC_VER => 1100
WIN32_LEAN_AND_MEAN=WIN32_LEAN_AND_MEAN => 1
__attribute__=__attribute__(x)
WINAPI=WINAPI => __stdcall
SOUNDTOUCHDLL_API=SOUNDTOUCHDLL_API => __declspec(dllimport)
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
__LINE__=__LINE__
_WIN32=_WIN32 => 1
_M_I86=_M_I86 => 1
__x86_64__=__x86_64__ => 1
__COUNTER__=__COUNTER__
_NATIVE_WCHAR_T_DEFINED=_NATIVE_WCHAR_T_DEFINED => 1
M_I86=M_I86 => 1
__FILE__=__FILE__
_CHAR_UNSIGNED=_CHAR_UNSIGNED => 1
__cplusplus=__cplusplus => 1
